/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class myjni_TestJNICallBackMethod */

#ifndef _Included_myjni_TestJNICallBackMethod
#define _Included_myjni_TestJNICallBackMethod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     myjni_TestJNICallBackMethod
 * Method:    nativeMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_myjni_TestJNICallBackMethod_nativeMethod
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
