/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class myjni_TestJNIConstructor */

#ifndef _Included_myjni_TestJNIConstructor
#define _Included_myjni_TestJNIConstructor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     myjni_TestJNIConstructor
 * Method:    getIntegerObject
 * Signature: (I)Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_myjni_TestJNIConstructor_getIntegerObject
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
