/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class myjni_TestJNIStaticVariable */

#ifndef _Included_myjni_TestJNIStaticVariable
#define _Included_myjni_TestJNIStaticVariable
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     myjni_TestJNIStaticVariable
 * Method:    modifyStaticVariable
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_myjni_TestJNIStaticVariable_modifyStaticVariable
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
