/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class myjni_TestJNICallBackMethodBase */

#ifndef _Included_myjni_TestJNICallBackMethodBase
#define _Included_myjni_TestJNICallBackMethodBase
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     myjni_TestJNICallBackMethodBase
 * Method:    nativeMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_myjni_TestJNICallBackMethodBase_nativeMethod
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
