/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class myjni_TestJNIPrimitive */

#ifndef _Included_myjni_TestJNIPrimitive
#define _Included_myjni_TestJNIPrimitive
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     myjni_TestJNIPrimitive
 * Method:    average
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_myjni_TestJNIPrimitive_average
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
