/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class myjni_TestJNIPrimitiveArray */

#ifndef _Included_myjni_TestJNIPrimitiveArray
#define _Included_myjni_TestJNIPrimitiveArray
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     myjni_TestJNIPrimitiveArray
 * Method:    sumAndAverage
 * Signature: ([I)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_myjni_TestJNIPrimitiveArray_sumAndAverage
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
